export const LEAGUE_ACTIONS = {
  SET_LEAGUES: 'SET_LEAGUES',
  SET_CURRENT_LEAGUE: 'SET_CURRENT_LEAGUE',
};

export const TEAM_ACTIONS = {
  SET_TEAM: 'SET_TEAM',
};

export const PLAYER_ACTIONS = {
  SET_PLAYER: 'SET_PLAYER',
};
